### ISSUE TITLE
add+各大互联网公司架构演进之路汇总

### ISSUE THREAD

**Issue by HDHunter** [Juude/Awesome-Android-Architecture#8]
https://mp.weixin.qq.com/s?__biz=MzI3NzE0NjcwMg==&mid=2650123329&idx=1&sn=8711199ca8d0e0b61d5083feacc15794&chksm=f36bb160c41c38768e110888c0020e8b97529241cf7ba275af80a8a8a048347f639fbd104fcf&mpshare=1&scene=23&srcid=#rd

**Comment by Juude** [comment]
内容很赞，
但是这个项目主要收集android项目
